name: Deploy Candy Clash

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Dosyalari indir
        uses: actions/checkout@v4

      - name: GitHub Pages ayarla
        uses: actions/configure-pages@v5

      - name: Siteyi yukle
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Yayınla
        uses: actions/deploy-pages@v4
